### ISSUE TITLE
Figma

### ISSUE THREAD

**Issue by Siivi** [Swissgroover/Bob-Marley#2]

**Comment by siily15** [comment]
![Bob Marley (1)](https://user-images.githubusercontent.com/55434210/70987873-6a2beb80-20c9-11ea-8390-53bf030b2d8e.png)

**Comment by siily15** [comment]
![Pictures (1)](https://user-images.githubusercontent.com/55434210/70988433-82503a80-20ca-11ea-9e8c-1dcede866ec4.png)

**Comment by siily15** [comment]
![Bob (1)](https://user-images.githubusercontent.com/55434210/70988455-909e5680-20ca-11ea-8992-d3135b98d2dc.png)

**Comment by siily15** [comment]
![Bob (4)](https://user-images.githubusercontent.com/55434210/70994004-e88e8a80-20d5-11ea-8b35-d742052a2f53.png)
