### ISSUE TITLE
Bob info

### ISSUE THREAD

**Issue by Siivi** [Swissgroover/Bob-Marley#3]
elu ja olu

**Comment by sanderrandmets** [comment]
Bob Marley was a Jamaican singer and songwriter. Marley's contributions to music increased the visibility of Jamaican music worldwide, and made him a global figure in popular culture for over a decade. Born in Nine Mile, British Jamaica, Marley began his professional musical career in 1963, after forming Bob Marley and the Wailers. The group released its debut studio album The Wailing Wailers in 1965, which contained the single "One Love/People Get Ready".

**Comment by sanderrandmets** [comment]
Bob Marley:
* was a Jamaican singer and songwriter.
* he contributions to music increased the visibility of Jamaican music worldwide
* born in Nine Mile, British Jamaica
* Marley began his professional musical career in 1963, after forming Bob Marley and the Wailers.
* The group released its debut studio album The Wailing Wailers in 1965

**Comment by Siivi** [comment]
"Marley wasn't singing about how peace could come easily to the World but rather how hell on Earth comes too easily to too many. His songs were his memories; he had lived with the wretched, he had seen the downpressers and those whom they pressed down."
 – Mikal Gilmore, Rolling Stone
